# ref: https://yarnpkg.com/configuration/yarnrc
defaultSemverRangePrefix: "~"
enableConstraintsChecks: true
enableGlobalCache: true
enableTelemetry: false
nmMode: hardlinks-local
nodeLinker: node-modules

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
