# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: 'redis'

services:
  redis:
    image: redis:8-alpine
    restart: always
    volumes:
      - redis-storage:/data
    networks:
      - redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
    # command: ["sleep", "10000"] # delay start for secrets fetching

volumes:
  redis-storage:
    driver: local

networks:
  redis:
    driver: bridge
    name: redis
