# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: 'nathans-64gb-mbp'

# kickstart this by:
# cd ~/src/portainer-stacks/hosts/Nathans-64GB-MBP/ && docker compose up -d -f ./docker-compose.yaml
# create the account on https://localhost:10202
# go to stacks and create a new stack referencing this, portainer will adopt it

services:
  portainer:
    ports:
      - # todo: do we need this?
        10201:8000
      - # https web api
        10202:9443
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: portainer/portainer-ce:lts
  n8n:
    stdin_open: true
    tty: true
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n

volumes:
  portainer_data:
    external: true
    name: portainer_data
  n8n_data:
    external: true
    name: n8n_data
# services:
#   agent:
#     image: portainer/agent
#     environment:
#       AGENT_CLUSTER_ADDR: tasks.agent
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /var/lib/docker/volumes:/var/lib/docker/volumes
#     ports:
#       - target: 9001
#         published: 9001
#         protocol: tcp
#         mode: host
#     networks:
#       - portainer_agent
#     deploy:
#       mode: global
#       placement:
#         constraints: [node.platform.os == linux]
# networks:
#   portainer_agent:
#     driver: overlay
#     attachable: true
