# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: 'nathans-64gb-mbp-n8n'

# Set in env on portainer:
# - GITHUB_TOKEN = <pat portainer uses>
# - GITHUB_REPO_OWNER = nsheaps
# - GITHUB_REPO_NAME = portainer-stacks
# - OP_SERVICE_ACCOUNT_TOKEN

x-shared: &shared
  restart: always
  image: docker.n8n.io/n8nio/n8n
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE_FILE=/run/secrets/postgres_db
    - DB_POSTGRESDB_USER_FILE=/run/secrets/postgres_user
    - DB_POSTGRESDB_PASSWORD_FILE=/run/secrets/postgres_password
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_ENCRYPTION_KEY_FILE=/run/secrets/n8n_encryption_key
  links:
    - postgres
    - redis
  volumes:
    - n8n_storage:/home/node/.n8n
    - secrets_volume:/run/secrets:ro
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
    secrets-init:
      condition: service_completed_successfully

services:
  # Portainer-ce doesn't support mounting from the local directory.
  # If using agent, we'd need to download the repo from git like this
  # https://github.com/portainer/portainer/issues/6390#issuecomment-1100954657
  # In theory we could change portainer's volume to persist to disk, but that doesn't work
  # for agents (where the agent runs the stack instead of the root instance, not typical of
  # docker-compose setups
  git-checkout:
    image: bitnami/git:latest
    working_dir: /temp
    environment:
      - GITHUB_TOKEN_FILE=/run/secrets/github_token
    command: >
      bash -c "
        set -euo pipefail
        export GITHUB_TOKEN="$(cat $GITHUB_TOKEN_FILE)"
        export GITHUB_REPO_OWNER="$(cat $GITHUB_OWNER_FILE)
        export GITHUB_REPO_NAME="$(cat $GITHUB_REPO_NAME_FILE)"
        find /temp -mindepth 1 -delete &&
        find /files -mindepth 1 -delete &&
        git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}.git &&
        cp -R "./${GITHUB_REPO_NAME}/." /mnt/portainer-stacks
      "
    volumes:
      - portainer_stacks:/mnt/portainer-stacks

  # Init container to fetch secrets from 1Password
  secrets-init:
    image: 1password/op:2
    environment:
      # OP_SERVICE_ACCOUNT_TOKEN should be set in Portainer as stack environment variable
      - OP_SERVICE_ACCOUNT_TOKEN=${OP_SERVICE_ACCOUNT_TOKEN}
    volumes:
      - secrets_volume:/run/secrets:ro
      - portainer_stacks:/mnt/portainer-stacks
    depends_on:
      git-checkout:
        condition: service_completed_successfully
    # command: ["/bin/bash", "/mnt/portainer-stacks/hosts/Nathans-64GB-MBP/scripts/fetch-secrets.sh"]
    command: '/bin/true'

  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_root_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_root_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
      - db_storage:/var/lib/postgresql/data
      - secrets_volume:/run/secrets:ro
      - portainer_stacks:/mnt/portainer-stacks
      - type: volume
        source: portainer_stacks
        target: /docker-entrypoint-initdb.d/init-postgres.sh
        volume:
          subpath: hosts/Nathans-64GB-MBP/scripts/init-postgres.sh
      # - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:ro
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U postgres -d n8n',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      secrets-init:
        condition: service_completed_successfully

  redis:
    image: redis:8-alpine
    restart: always
    volumes:
      - redis_storage:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *shared
    ports:
      - "${N8N_PORT:-5678}:5678"

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n

volumes:
  portainer_stacks:
  db_storage:
    driver: local
  n8n_storage:
    driver: local
  redis_storage:
    driver: local
  secrets_volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m,mode=0755
