# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: 'Nathans-64GB-MBP'

services:
  pause:
    image: registry.k8s.io/pause
