# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: 'portainer'

# kickstart this by:
# cd ~/src/portainer-stacks/hosts/_portainer/ && docker compose -f ./docker-compose.yaml up -d
# create the account on https://localhost:10202
# do not sync this stack with the portainer web ui, it will kill itself when it tries to reload

services:
  portainer:
    ports:
      - # https web api
        10202:9443
      - 10201:8000
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: portainer/portainer-ce:lts

volumes:
  portainer_data:
    external: true
    name: portainer_data
