name: beszel

services:
  beszel-hub:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://beszel.heaps.cloud
    healthcheck:
      # The URL is relative to the container, not the host
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 5s # Check 5 seconds after the container starts
      interval: 60s # Then check every 60 seconds after that
    networks:
      - cloudflared
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

# https://docs.docker.com/engine/storage/drivers/
volumes:
  beszel_data:
    driver: local
  beszel_socket:
    driver: local

networks:
  cloudflared:
    external: true
