name: beszel

services:
  beszel-hub:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - cloudflared
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  # We'll deploy the agent using a binary instead of a container:
  # https://beszel.dev/guide/agent-installation#binary
  # beszel-agent:
  #   image: henrygd/beszel-agent:latest
  #   container_name: beszel-agent
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - ./beszel_agent_data:/var/lib/beszel-agent
  #     - ./beszel_socket:/beszel_socket
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     LISTEN: /beszel_socket/beszel.sock
  #     HUB_URL: http://localhost:8090
  #     TOKEN: <token>
  #     KEY: "<key>"

# https://docs.docker.com/engine/storage/drivers/
volumes:
  beszel_data:
    driver: local
  beszel_socket:
    driver: local

networks:
  cloudflared:
    external: true
